### PR TITLE
its working trust me.

### PR DESCRIPTION
**Pull request by qingzen**
Add lib
added support

### CODE REVIEW

**Comment by NhanAZ** [comment]
Thank you for your kindness but your code is really bad...

**Comment by qingzen** [comment]
yeah im using your old code.

**Comment by NhanAZ** [comment]
That's exactly the code from previous versions
I changed it to make it better
There's no reason to reuse the old code

**Comment by qingzen** [comment]
ok im gonna use ur new code then

**Comment by qingzen** [comment]
can i pull req again, or i should do not?

**Comment by NhanAZ** [comment]
You can, I'll review

**Comment by qingzen** [comment]
can u see first, is this ok to pull [link](https://github.com/zsfell/CustomJoinSound/blob/master/src/NhanAZ/CustomJoinSound/Main.php)

**Comment by NhanAZ** [comment]
What makes you use `libRegRsp` instead of `libBedrock`?
`libRegRsp` has been archived and is no longer maintained for use

**Comment by qingzen** [comment]
I think it's simpler code, i will not pull req and thank for your attenions.

**Comment by NhanAZ** [comment]
The new code only takes 2 lines to register and unregister
The old code took 6 lines to do the same thing
Why do you think the old code is simpler?

**Pull request closed without merging**
