### PR TITLE
use libCustomPack by jasonwynn10

### PR DESCRIPTION
**Pull request by 0xliam627**

### CODE REVIEW

**Comment by NhanAZ** [comment]
@DavidGlitch04 Please resolve this issue. Thanks.
https://crash.pmmp.io/view/6960785

**Comment by 0xliam627** [comment]
Do you use dev 2 on poggit ?

**Comment by NhanAZ** [comment]
I use this https://poggit.pmmp.io/ci/nhanaz-pm-pl/CustomJoinSound/~/pr:5

**Comment by DavidGlitch04** [comment]
Retry in libCustomPack dev3

**Comment by 0xliam627** [comment]
Please retry

**Review by NhanAZ — APPROVED** [review]
Thanks for your contribution. Have a nice day!

**Pull request merged**
